/* file: msg.c, automatically generated by gencanoe.exe, Version: 5.02 */
/* configuration read from: C:\Users\nituser\AppData\Local\Temp\Cfg_Gen-1729668396287-7\OsProxyFiles-1729669053820-0\Os_ActiveEcuC.arxml.oil */
/* generation at  : Wed Oct 23 09:37:37 2024 */
/* Unlimited license 1234567890 for CANoeEmu Generic License */
/* Implementation: CANoeOsekEmu */
/* Version of general code: 5.31 */

#if defined USE_QUOTE_INCLUDES
 #include "vrm.h"
#else
 #include <vrm.h>
#endif
#define osdVrmGenMajRelNum 5
#define osdVrmGenMinRelNum 2
#if defined USE_QUOTE_INCLUDES
 #include "vrm.h"
#else
 #include <vrm.h>
#endif

#include <Os.h>


/* END OF C:\Users\nituser\Desktop\Autosar homework\M2\E1\_E1_SoftwareComponents\Appl\GenDataVtt\msg.c */

